# Generated by Django 3.2.5 on 2021-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nayakhabar', '0002_auto_20210806_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
